### PR TITLE
typo fixes for the javalite.io document

### PR DESCRIPTION
**Pull request by christilden**

### CODE REVIEW

**Comment by ipolevoy** [comment]
That kind you for the contribution!

**Comment by ipolevoy** [comment]
That was an autocomplete that went haywire! Thank you for the contribution, lol!

**Comment by christilden** [comment]
No problem.  It's such a great product, I wish I could contribute more!

**Comment by ipolevoy** [comment]
every contribution is welcome, see if there is something you like.

**Pull request merged**
